export default {
  "login": "AdminAbhi",
  "id": 32995208,
  "node_id": "MDQ6VXNlcjMyOTk1MjA4",
  "avatar_url": "https://avatars.githubusercontent.com/u/32995208?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/AdminAbhi",
  "html_url": "https://github.com/AdminAbhi",
  "followers_url": "https://api.github.com/users/AdminAbhi/followers",
  "following_url": "https://api.github.com/users/AdminAbhi/following{/other_user}",
  "gists_url": "https://api.github.com/users/AdminAbhi/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/AdminAbhi/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/AdminAbhi/subscriptions",
  "organizations_url": "https://api.github.com/users/AdminAbhi/orgs",
  "repos_url": "https://api.github.com/users/AdminAbhi/repos",
  "events_url": "https://api.github.com/users/AdminAbhi/events{/privacy}",
  "received_events_url": "https://api.github.com/users/AdminAbhi/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Abhishek Abhi",
  "company": "TATA Consultancy Services",
  "blog": "https://www.hackerrank.com/Abhi_Shake_Abhi?hr_r=1",
  "location": "Bokaro Steel City, Jharkhand, India.",
  "email": null,
  "hireable": true,
  "bio": "\r\n    Open Source is love.\r\n",
  "twitter_username": "Abhi_Shake_Abhi",
  "public_repos": 25,
  "public_gists": 1,
  "followers": 5,
  "following": 7,
  "created_at": "2017-10-22T06:03:10Z",
  "updated_at": "2021-10-13T14:05:54Z"
};
