export default [
  {
    "login": "ashersuman",
    "id": 34215470,
    "node_id": "MDQ6VXNlcjM0MjE1NDcw",
    "avatar_url": "https://avatars.githubusercontent.com/u/34215470?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ashersuman",
    "html_url": "https://github.com/ashersuman",
    "followers_url": "https://api.github.com/users/ashersuman/followers",
    "following_url": "https://api.github.com/users/ashersuman/following{/other_user}",
    "gists_url": "https://api.github.com/users/ashersuman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ashersuman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ashersuman/subscriptions",
    "organizations_url": "https://api.github.com/users/ashersuman/orgs",
    "repos_url": "https://api.github.com/users/ashersuman/repos",
    "events_url": "https://api.github.com/users/ashersuman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ashersuman/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "RajawatBanna",
    "id": 45819488,
    "node_id": "MDQ6VXNlcjQ1ODE5NDg4",
    "avatar_url": "https://avatars.githubusercontent.com/u/45819488?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/RajawatBanna",
    "html_url": "https://github.com/RajawatBanna",
    "followers_url": "https://api.github.com/users/RajawatBanna/followers",
    "following_url": "https://api.github.com/users/RajawatBanna/following{/other_user}",
    "gists_url": "https://api.github.com/users/RajawatBanna/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/RajawatBanna/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/RajawatBanna/subscriptions",
    "organizations_url": "https://api.github.com/users/RajawatBanna/orgs",
    "repos_url": "https://api.github.com/users/RajawatBanna/repos",
    "events_url": "https://api.github.com/users/RajawatBanna/events{/privacy}",
    "received_events_url": "https://api.github.com/users/RajawatBanna/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Dheeraj-01",
    "id": 54698983,
    "node_id": "MDQ6VXNlcjU0Njk4OTgz",
    "avatar_url": "https://avatars.githubusercontent.com/u/54698983?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Dheeraj-01",
    "html_url": "https://github.com/Dheeraj-01",
    "followers_url": "https://api.github.com/users/Dheeraj-01/followers",
    "following_url": "https://api.github.com/users/Dheeraj-01/following{/other_user}",
    "gists_url": "https://api.github.com/users/Dheeraj-01/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Dheeraj-01/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Dheeraj-01/subscriptions",
    "organizations_url": "https://api.github.com/users/Dheeraj-01/orgs",
    "repos_url": "https://api.github.com/users/Dheeraj-01/repos",
    "events_url": "https://api.github.com/users/Dheeraj-01/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Dheeraj-01/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "anurags10",
    "id": 54910091,
    "node_id": "MDQ6VXNlcjU0OTEwMDkx",
    "avatar_url": "https://avatars.githubusercontent.com/u/54910091?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/anurags10",
    "html_url": "https://github.com/anurags10",
    "followers_url": "https://api.github.com/users/anurags10/followers",
    "following_url": "https://api.github.com/users/anurags10/following{/other_user}",
    "gists_url": "https://api.github.com/users/anurags10/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/anurags10/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/anurags10/subscriptions",
    "organizations_url": "https://api.github.com/users/anurags10/orgs",
    "repos_url": "https://api.github.com/users/anurags10/repos",
    "events_url": "https://api.github.com/users/anurags10/events{/privacy}",
    "received_events_url": "https://api.github.com/users/anurags10/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "SanchitaGupta0224",
    "id": 66419712,
    "node_id": "MDQ6VXNlcjY2NDE5NzEy",
    "avatar_url": "https://avatars.githubusercontent.com/u/66419712?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SanchitaGupta0224",
    "html_url": "https://github.com/SanchitaGupta0224",
    "followers_url": "https://api.github.com/users/SanchitaGupta0224/followers",
    "following_url": "https://api.github.com/users/SanchitaGupta0224/following{/other_user}",
    "gists_url": "https://api.github.com/users/SanchitaGupta0224/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SanchitaGupta0224/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SanchitaGupta0224/subscriptions",
    "organizations_url": "https://api.github.com/users/SanchitaGupta0224/orgs",
    "repos_url": "https://api.github.com/users/SanchitaGupta0224/repos",
    "events_url": "https://api.github.com/users/SanchitaGupta0224/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SanchitaGupta0224/received_events",
    "type": "User",
    "site_admin": false
  }
];
